import SideBar from '@/components/SideBar'
import './globals.css'
import { Inter } from 'next/font/google'
import Provider from '@/context/Provider'
import { getServerSession } from 'next-auth'
import { authOptions, getServerAuthSession } from '@/server/auth'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    const session = await getServerAuthSession()
    // const session = await getServerSession(authOptions)
    return (
        <html lang='en'>
            <body>
                <Provider>
                    <main
                        className={`${inter.className} flex md:mx-14 lg:mx-10 mx-5`}
                    >
                        <div className='grow relative'>
                            <SideBar session={session} />
                        </div>
                        <div className='m-auto grow'>{children}</div>
                    </main>
                </Provider>
            </body>
        </html>
    )
}
